#!/usr/bin/env python3
"""Generate the deterministic license bundle for shipped dependencies."""

import argparse
import hashlib
import json
import os
import pathlib
import subprocess
import sys


ROOT = pathlib.Path(__file__).resolve().parent.parent
LICENSE_PREFIXES = ("license", "copying", "notice")
CA_BUNDLE_DIR = ROOT / "third_party/ca-certificates-bundle"
VETTED_SHA256 = {
    "MIT.txt": "232f7df28fcccad44e6d049dd3408721a61daeaa682c5e9dd0df4283a48d2f2e",
    "MPL-2.0.txt": "3f3d9e0024b1921b067d6f7f88deb4a60cbe7a78e76c64e3f1d7fc3b779b9d04",
    "PROVENANCE": "e00577c4db3dfb11c18aea9fc129676033a95eb32237452d02dbdad325c5d092",
}
GO_LICENSE_SHA256 = {
    "LICENSE": "911f8f5782931320f5b8d1160a76365b83aea6447ee6c04fa6d5591467db9dad",
    "PATENTS": "96f408bfae65bf137fc2525d3ecb030271c50c1e90799f87abf8846d8dd505cc",
}


def checked_text(path: pathlib.Path, expected_sha256: str | None = None) -> str:
    data = path.read_bytes()
    if expected_sha256 and hashlib.sha256(data).hexdigest() != expected_sha256:
        raise RuntimeError(f"vetted license source changed: {path}")
    return data.decode("utf-8").replace("\r\n", "\n").rstrip()


def license_files(directory: pathlib.Path) -> list[pathlib.Path]:
    files = sorted(
        (
            path
            for path in directory.iterdir()
            if path.is_file()
            and path.name.lower().startswith(LICENSE_PREFIXES)
        ),
        key=lambda path: path.name,
    )
    if not files:
        raise RuntimeError(f"no root license file in dependency {directory}")
    return files


def go_dependencies() -> list[tuple[str, str, pathlib.Path]]:
    template = (
        "{{with .Module}}{{if not .Main}}"
        "{{.Path}}\t{{.Version}}\t{{.Dir}}{{end}}{{end}}"
    )
    dependencies: set[tuple[str, str, pathlib.Path]] = set()
    for goos, goarch in (
        ("linux", "amd64"),
        ("linux", "arm64"),
        ("darwin", "amd64"),
        ("darwin", "arm64"),
    ):
        output = subprocess.run(
            [
                "go", "list", "-deps", "-f", template,
                "./cmd/oonfeewrtd", "./tools/recoverycheck",
            ],
            cwd=ROOT,
            env={**os.environ, "CGO_ENABLED": "0", "GOOS": goos, "GOARCH": goarch},
            check=True,
            capture_output=True,
            text=True,
        ).stdout
        dependencies.update(
            (path, version, pathlib.Path(directory))
            for line in output.splitlines()
            if line
            for path, version, directory in [line.split("\t", 2)]
        )
    return sorted(dependencies, key=lambda item: (item[0], item[1]))


def ui_dependencies() -> list[tuple[str, str, pathlib.Path]]:
    lock = json.loads((ROOT / "ui/package-lock.json").read_text())
    packages = lock["packages"]
    pending = list(packages[""]["dependencies"])
    names: set[str] = set()
    while pending:
        name = pending.pop()
        if name in names:
            continue
        key = f"node_modules/{name}"
        package = packages.get(key)
        if package is None:
            raise RuntimeError(f"production dependency {name} is absent from package-lock.json")
        names.add(name)
        pending.extend(package.get("dependencies", {}))

    return [
        (name, packages[f"node_modules/{name}"]["version"], ROOT / "ui/node_modules" / name)
        for name in sorted(names)
    ]


def go_toolchain() -> tuple[str, list[pathlib.Path]]:
    environment = json.loads(
        subprocess.run(
            ["go", "env", "-json", "GOROOT", "GOVERSION"],
            cwd=ROOT,
            check=True,
            capture_output=True,
            text=True,
        ).stdout
    )
    expected = next(
        line.split()[1]
        for line in (ROOT / "go.mod").read_text(encoding="utf-8").splitlines()
        if line.startswith("toolchain ")
    )
    if environment["GOVERSION"] != expected:
        raise RuntimeError(
            f"release toolchain is {environment['GOVERSION']}; expected {expected} from go.mod"
        )
    root = pathlib.Path(environment["GOROOT"])
    return expected, [root / "LICENSE", root / "PATENTS"]


def add_section(
    sections: list[str], heading: str, label: str, path: pathlib.Path, expected_sha256: str | None = None
) -> None:
    sections.extend(
        [
            "=" * 78,
            heading,
            f"{label}: {path.name}",
            "-" * 78,
            checked_text(path, expected_sha256),
            "",
        ]
    )


def generate() -> str:
    sections = [
        "THIRD-PARTY SOFTWARE LICENSES",
        "",
        "Generated by tools/generate-third-party-licenses.py from the pinned Go",
        "toolchain and CA bundle plus the locked controller and production UI dependencies.",
        "Do not edit this file directly.",
        "",
    ]
    go_version, go_license_paths = go_toolchain()
    for path in go_license_paths:
        add_section(
            sections,
            f"Go toolchain/runtime and standard library: {go_version}",
            "Notice file",
            path,
            GO_LICENSE_SHA256[path.name],
        )

    for filename in ("PROVENANCE", "MPL-2.0.txt", "MIT.txt"):
        add_section(
            sections,
            "Runtime CA roots: Alpine ca-certificates-bundle 20260611-r0",
            "Vetted source file",
            CA_BUNDLE_DIR / filename,
            VETTED_SHA256[filename],
        )

    dependencies = [
        *(('Go module', name, version, directory) for name, version, directory in go_dependencies()),
        *(('UI package', name, version, directory) for name, version, directory in ui_dependencies()),
    ]
    for ecosystem, name, version, directory in dependencies:
        for license_path in license_files(directory):
            add_section(
                sections,
                f"{ecosystem}: {name} {version}",
                "License file",
                license_path,
            )
    return "\n".join(sections)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("output", nargs="?", default="THIRD_PARTY_LICENSES")
    args = parser.parse_args()
    target = ROOT / args.output
    content = generate()
    if args.check:
        if not target.is_file() or target.read_text(encoding="utf-8") != content:
            print(f"{target}: regenerate with tools/generate-third-party-licenses.py", file=sys.stderr)
            return 1
        return 0
    target.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
