package daemon

import (
	"errors"
	"fmt"
	"io"
	"os"

	"golang.org/x/term"

	"github.com/aiden0rchad/oonfeewrt/internal/secrets"
)

// ErrNoPassphraseSource is returned when there is neither a passphrase file nor
// a terminal to prompt on.
//
// This is a refusal, not a fallback. The alternatives — an unencrypted keyring,
// a fixed default, a key derived from the hostname — all end with device
// credentials readable from a backup, and every one of them would look like it
// worked.
var ErrNoPassphraseSource = errors.New(
	"daemon: no passphrase available — stdin is not a terminal and " +
		EnvPassphraseFile + " is not set. Either run the daemon attached to a " +
		"terminal for the first-time prompt, or point " + EnvPassphraseFile +
		" at a file with mode 600 (see the unattended-boot tradeoff in the docs)")

// passphraseFor obtains the operator passphrase.
//
// firstRun changes the interactive path only: a new keyring asks twice, because
// a typo there is not a login failure, it is a keyring nobody can ever open. An
// existing keyring asks once and lets the unwrap be the check.
func passphraseFor(cfg Config, firstRun bool, in *os.File, out io.Writer) ([]byte, error) {
	if cfg.PassphraseFile != "" {
		return secrets.ReadPassphraseFile(cfg.PassphraseFile)
	}
	fd := int(in.Fd())
	if !term.IsTerminal(fd) {
		return nil, ErrNoPassphraseSource
	}
	if !firstRun {
		return promptOnce(fd, out, "Operator passphrase: ")
	}

	fmt.Fprintf(out, "No keyring found in %s — creating one.\n", cfg.DataDir)
	fmt.Fprintf(out, "This passphrase protects controller credentials and wireless keys. "+
		"There is no recovery if it is lost.\n")
	first, err := promptOnce(fd, out, "New operator passphrase: ")
	if err != nil {
		return nil, err
	}
	again, err := promptOnce(fd, out, "Repeat passphrase: ")
	if err != nil {
		return nil, err
	}
	if string(first) != string(again) {
		clear(first)
		clear(again)
		return nil, errors.New("daemon: the two passphrases do not match")
	}
	clear(again)
	return first, nil
}

func promptOnce(fd int, out io.Writer, prompt string) ([]byte, error) {
	fmt.Fprint(out, prompt)
	pass, err := term.ReadPassword(fd)
	fmt.Fprintln(out)
	if err != nil {
		return nil, fmt.Errorf("daemon: read passphrase: %w", err)
	}
	if len(pass) == 0 {
		return nil, secrets.ErrNoPassphrase
	}
	return pass, nil
}

// unlockHint turns a failed keyring unlock into a next step.
//
// The underlying error is accurate — the passphrase is wrong, or the keyring is
// corrupt — and answers none of "what do I do now". In practice the commonest
// cause is that the passphrase was never typed by a human at all: it was
// generated by an automated run and written to a file, and the interactive
// prompt has no way of saying so. An operator then sits at a prompt with
// nothing they could possibly enter.
//
// Only added when the passphrase came from that prompt. Someone who already
// passed -passphrase-file has a different problem, and telling them to use the
// flag they just used is noise dressed as help.
func unlockHint(cfg Config, path string, err error) error {
	if cfg.PassphraseFile != "" {
		return err
	}
	return fmt.Errorf("%w\n\nThe keyring at %s could not be unlocked. If this "+
		"controller was set up by an automated run, its passphrase may never "+
		"have been typed by anyone — pass the file instead:\n"+
		"  -passphrase-file /path/to/passphrase   (must be mode 0600)\n"+
		"or OONFEE_PASSPHRASE_FILE. There is no recovery if the passphrase is "+
		"genuinely lost; restore a matching database-and-keyring backup or reset "+
		"the controller and re-adopt the devices", err, path)
}
